apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lolyalty-system-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: loyalty-system-service
              port: 
                number: 8080
