apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.name" . }}-config-map
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  dbname: "{{ .Values.mysql.mysqlDatabase }}"
  dbAddress: "{{ .Values.mysql.host }}"
  dbPort: "{{ .Values.mysql.service.port }}"
  dbDriver: "{{ .Values.mysql.mysqlDriver }}"
  redisAddress: "{{ .Values.redis.host }}"
  redisPort: "{{ .Values.redis.port }}"
  redisPassword: ""
  redisDBNumber: "{{ .Values.redis.dbNumber }}"
  redisStream: "{{ .Values.redis.stream }}"