replicaCount: 1

image:
  hostname: docker.io
  repository: /tramak/shop-service
  tag: latest
  pullPolicy: IfNotPresent  

service:
  type: NodePort
  protocol: TCP
  port: 8080
  name: web

ingress:
  className: nginx
  port: 8080

mysql:
  enabled: true
  host: shop-service-mysql  
  mysqlDriver: mysql
  mysqlDatabase: shop
  imagePath: mysql:8.0
  service:
    port: 3306
    name: mysql
    type: ClusterIP
  initdbScripts:
    initdb.sql: |-
      CREATE DATABASE IF NOT EXISTS shop DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS loyalty_system DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS warehouses DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS orders DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS notifications DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS delivery DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS accounts DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS payments DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE USER 'admin'@'%' IDENTIFIED BY 'test';
      GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
  primary:    
    persistence:
      enabled: false
      storageClass: standard
  terminationGracePeriodSeconds: 10
  storeName: mysql-store

redis:
  host: redis-server.default.svc.cluster.local
  port: 6379
  dbNumber: 0
  stream: notification

redirectAuthUrl: http://arch.homework
redirectAuthServiceUrl: http://authenticator.default.svc.cluster.local:8080
billingServiceUrl: http://billing-service.default.svc.cluster.local:8080
ordersServiceUrl: http://orders-service.default.svc.cluster.local:8080
notificationServiceUrl: http://notification-service.default.svc.cluster.local:8080
paymentServiceUrl: http://payment.default.svc.cluster.local:8080
warehouseServiceUrl: http://warehouse-service.default.svc.cluster.local:8080
deliveryServiceUrl: http://delivery-service.default.svc.cluster.local:8080
shopServiceUrl: http://shop-service.default.svc.cluster.local:8080

mysqlDatabaseWarehouse: warehouses
mysqlDatabaseOrders: orders
mysqlDatabaseNotifications: notifications
mysqlDatabaseDelivery: delivery
mysqlDatabaseAccounts: accounts
mysqlDatabasePayments: payments
mysqlDatabaseLoyaltySystem: loyalty_system