{{- $fullName := include "shop-service.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullName }}-app
  template:
    metadata:
      labels:
        app: {{ $fullName }}-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "shop-service.image" . }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: {{ $fullName }}-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-config-map
                  key: dbname
            - name: DB_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-config-map
                  key: dbAddress
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-config-map
                  key: dbPort
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-config-map
                  key: dbDriver
            - name: REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-config-map
                  key: redirectAuthUrl
            - name: REDIRECT_SERViCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-config-map
                  key: redirectAuthServiceUrl
      volumes:
      - name: {{ $fullName }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ $fullName }}-pv-claim                                                                                                                                            
