apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop-service.name" . }}-config-map
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  dbname: "{{ .Values.mysql.mysqlDatabase }}"
  dbAddress: "{{ .Values.mysql.host }}"
  dbPort: "{{ .Values.mysql.service.port }}"
  dbDriver: "{{ .Values.mysql.mysqlDriver }}"
  redirectAuthUrl: "{{ .Values.redirectAuthUrl }}"
  redirectAuthServiceUrl: "{{ .Values.redirectAuthServiceUrl }}"
  billingServiceUrl: "{{ .Values.billingServiceUrl }}"
  ordersServiceUrl: "{{ .Values.ordersServiceUrl }}"
  notificationServiceUrl: "{{ .Values.notificationServiceUrl }}"
  redisAddress: "{{ .Values.redis.host }}"
  redisPort: "{{ .Values.redis.port }}"
  redisPassword: ""
  redisDBNumber: "{{ .Values.redis.dbNumber }}"
  redisStream: "{{ .Values.redis.stream }}"