kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['error', 'priority']
      group_wait: 10s
      repeat_interval: 30m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: shop-service@email.com
        send_resolved: false
        from: shop-service-notificator@email.com
        smarthost: smtp.eample.com:25
        require_tls: false