{{- $fullName := include "orders-service.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: {{ $fullName }}-service
              port: 
                number: {{ .Values.ingress.port }}
