apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: tramak/payment-service:latest
          ports:
            - containerPort: 8080
              name: payment
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: BILLING_SERViCE_URL
              valueFrom:
                configMapKeyRef:
                  name: shop-service-config-map
                  key: billingServiceUrl                                                                                                                                           
