{{- $fullName := include "loyalty-system.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullName }}-app
  template:
    metadata:
      labels:
        app: {{ $fullName }}-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "loyalty-system.image" . }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: dbPassword
            - name: DB_NAME
              value: "loyalty_system"
            - name: DB_ADDRESS
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_DRIVER
              value: "mysql"                                                                                                                                                  
