apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loyalty-system.name" . }}-secrets
type: Opaque
stringData:
  dbUser: {{ .Values.mysql.mysqlUser }}
  dbPassword: {{ .Values.mysql.mysqlPassword }}