apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loyalty-system.name" . }}-mysql-statefulset
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.service.name }}
  serviceName: {{ .Values.mysql.service.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.service.name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.mysql.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Values.mysql.service.name }}
        image: {{ .Values.mysql.imagePath }}
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
        volumeMounts:
        - name: {{ .Values.mysql.storeName }}
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "loyalty-system.name" . }}-secrets
                key: mysqlRootPassword
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.mysql.storeName }}
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi