{{- $fullName := include "loyalty-system.name" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-pv-claim
  labels:
    app: {{ $fullName }}-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi