replicaCount: 1

image:
  hostname: docker.io
  repository: /tramak/billing-service
  tag: latest
  pullPolicy: IfNotPresent  

service:
  type: NodePort
  protocol: TCP
  port: 8080
  name: web

ingress:
  className: nginx
  port: 8080

mysql:
  enabled: true
  host: billing-service-mysql  
  mysqlDriver: mysql
  mysqlDatabase: orders
  imagePath: mysql:8.0
  service:
    port: 3306
    name: mysql
    type: ClusterIP
  initdbScripts:
    initdb.sql: |-
      CREATE DATABASE IF NOT EXISTS accounts DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE USER 'admin'@'%' IDENTIFIED BY 'test';
      GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
  primary:    
    persistence:
      enabled: false
      storageClass: standard
  terminationGracePeriodSeconds: 10
  storeName: mysql-store